setup:
  exp: 'mfxp23120'
  det_type: 'epix10k2M'
  root_dir: '/sdf/home/n/nathfrn/pypca'
  log_dir: '/sdf/home/n/nathfrn/pypca/scripts/logs'
  account: 'lcls'
  
dim_reduc:
  filename: '/sdf/data/lcls/ds/mfx/mfxp23120/scratch/nathfrn/pypca_models/pypca_model_91_2000_1000_500.h5'
  num_images: 2000
  num_gpus: 4
  start_run: 91
  max_run: 92
  loading_batch_size: 1000
  threshold: 0.99
  num_tries: 100
  grid_size: 40
  guiding_panel: 2
  type_of_embedding: 'umap'
  first_rank: 1
  
fit:
  start_run: 91
  max_run: 92
  start_offset: 0
  num_images: 2000
  batch_size: 500
  loading_batch_size: 2000
  num_components: 2000
  model_path: '/sdf/data/lcls/ds/mfx/mfxp23120/scratch/nathfrn/pypca_models/'
  num_gpus: 4
  num_nodes: 4
  lower_bound: -1
  upper_bound: -1
  
transform:
  start_run: 91
  max_run: 91
  start_offset: 0
  num_images: 2000
  batch_size: 500
  loading_batch_size: 2000
  model: '/sdf/data/lcls/ds/mfx/mfxp23120/scratch/nathfrn/pypca_models/pypca_model_91_92_2000_2000_500.h5'
  num_gpus: 4
  num_nodes: 4