setup:
  queue: 'milano'
  root_dir: '/sdf/data/lcls/ds/mfx/mfxp23120/scratch/test_btx'
  exp: 'mfxp23120'
  run: 5
  det_type: 'epix10k2M'
  cell: ''
  account: 'lcls:mfxp23120'

t_sne:
  filename: '/sdf/data/lcls/ds/mfx/mfxp23120/scratch/test_btx/pipca/pypca_model_1000_1000_100_n4.h5'
  num_images: 1000
  num_gpus: 4
  run: 91
  loading_batch_size: 2500
  threshold: 0.99
  num_tries: 500
  grid_size: 25
  guiding_panel: 5
  type_of_embedding: 'umap'
  
create_pypca_multinodes:
  start_offset: 0
  num_images: 1000
  run: 91
  batch_size: 100
  loading_batch_size: 2500
  num_components: 1000
  overwrite: True
  path: '/sdf/data/lcls/ds/mfx/mfxp23120/scratch/test_btx/pipca/'
  tag: '1000_1000_100_n4'
  training_percentage: 1
  smoothing_function: "id"
  num_gpus: 4
  compute_loss: 0
  compute_projected_images: 0
  num_nodes: 4
  
update_pypca_multinodes:
  run: 92
  start_offset: 0
  num_images: 500
  loading_batch_size: 250
  batch_size: 100
  lower_bound: -1
  upper_bound: -1
  model: '/sdf/data/lcls/ds/mfx/mfxp23120/scratch/test_btx/pipca/pypca_model_1000_500_500_n4.h5'
  num_gpus: 4
  num_nodes: 4
  
reduce_pypca_multinodes:
  run: 91
  start_offset: 0
  num_images: 2000
  loading_batch_size: 500
  batch_size: 500
  model: '/sdf/data/lcls/ds/mfx/mfxp23120/scratch/test_btx/pipca/pypca_model_2000_2000_500_n4.h5'
  num_gpus: 4
  num_nodes: 4