setup:
  exp: 'mfxx49820'
  det_type: 'epix10k2M'
  root_dir: '/sdf/home/n/nathfrn/pypca'
  log_dir: '/sdf/home/n/nathfrn/pypca/scripts/logs'
  account: 'lcls'

dim_reduc:
  filename: '/sdf/data/lcls/ds/mfx/mfxp23120/scratch/nathfrn/pypca_models/pypca_model_91_92_2000_2000_500.h5'
  num_images: 2000
  num_gpus: 4
  start_run: 91
  max_run: 92
  loading_batch_size: 1000
  threshold: 0.99
  num_tries: 1000
  grid_size: 50
  guiding_panel: 2
  type_of_embedding: 'umap'
  first_rank: 0
  
fit:
  start_run: 16
  max_run: 16
  start_offset: 0
  num_images: -1
  batch_size: 250
  loading_batch_size: 2500
  num_components: 15000
  model_path: '/sdf/data/lcls/ds/mfx/mfxx49820/scratch/nathfrn/pypca_models/'
  num_gpus: 4
  num_nodes: 8
  lower_bound: -1
  upper_bound: -1
  
transform:
  start_run: 16
  max_run: 16
  start_offset: 0
  num_images: -1
  batch_size: 250
  loading_batch_size: 2500
  model: '/sdf/data/lcls/ds/mfx/mfxx49820/scratch/nathfrn/pypca_models/pypca_model_16_16_-1_15000_250.h5'
  num_gpus: 4
  num_nodes: 8

compute_loss:
  start_run: 16
  max_run: 16
  start_offset: 0
  num_images: -1
  loading_batch_size: 2500
  model: '/sdf/data/lcls/ds/mfx/mfxx49820/scratch/nathfrn/pypca_models/pypca_model_16_16_-1_15000_250.h5'
  num_gpus: 4
  num_nodes: 8
  projections_filename: '/sdf/data/lcls/ds/mfx/mfxx49820/scratch/nathfrn/pypca_models/projections_16_16_37710_15000.h5'

compute_psnr_ssim:
  start_run: 16
  max_run: 16
  start_offset: 0
  num_images: -1
  loading_batch_size: 200
  model: '/sdf/data/lcls/ds/mfx/mfxx49820/scratch/nathfrn/pypca_models/pypca_model_16_16_-1_15000_250.h5'
  num_gpus: 4
  projections_filename: '/sdf/data/lcls/ds/mfx/mfxx49820/scratch/nathfrn/pypca_models/projections_16_16_37710_15000.h5'